### ISSUE TITLE
Already existing key

### ISSUE THREAD

**Issue by aceArt-GmbH** [philipaconrad/matrix-archiver-sqlite#4]
I am not sure why, but some rooms seem to crash on inserting into db.
Creating a new public room seems enough
```
$ python3 archive.py 
Connected to database: db.sqlite
MATRIX_HOST: 'http://192.168.22.140'
MATRIX_USER: '@root:192.168.22.140.'
MATRIX_PASSWORD: '****'
MATRIX_ROOM_IDS: '['']'
Signing into http://192.168.22.140...
Archiving Device list for user.
 |-- Skipping Device: 'None' (Device ID: 'UJOPXBBEST') because it has already been archived.
 |-- Skipping Device: 'Synapse Admin' (Device ID: 'EKAIXKWDRL') because it has already been archived.
 |-- Skipping Device: 'Synapse Admin' (Device ID: 'PRYOJLUKIP') because it has already been archived.
 |-- Skipping Device: 'None' (Device ID: 'Matrix Archiver') because it has already been archived.
Archiving Room: 'test' (Room ID: '!EtqWFvyCKhVcDnnRkn:192.168.22.140.')
 | Backing up room metadata...
 | Backing up list of room members...
 | Backing up list of room events...
 |-- No existing events backup for this room. Creating a new one...
 |---- Reading events from room 'test'…
 |---- Read 9 events...
Traceback (most recent call last):
  File "/home/user/matrix-archiver-sqlite/archive.py", line 372, in <module>
    add_rooms(client.get_rooms())
  File "<string>", line 2, in add_rooms
  File "/home/user/.local/lib/python3.10/site-packages/pony/orm/core.py", line 519, in new_func
    result = func(*args, **kwargs)
  File "/home/user/matrix-archiver-sqlite/archive.py", line 271, in add_rooms
    item = Event(room=r,
  File "/home/user/.local/lib/python3.10/site-packages/pony/orm/core.py", line 4720, in __init__
    if val in cache_indexes[attr]: throw(CacheIndexError,
  File "/home/user/.local/lib/python3.10/site-packages/pony/utils/utils.py", line 99, in throw
    raise exc
pony.orm.core.CacheIndexError: Cannot create Event: value '$HET6M1Oszn6iEBxHXzph1zznm22hBWwN5mAnFOVLV7U' for key event_id already exists
```

**Comment by aceArt-GmbH** [comment]
I assume my synapse database contains wrong/duplicate events.

```diff
-event_id = Required(str, unique=True)
+event_id = Required(str)
```
allows me to finish the export
